### ISSUE TITLE
Crash with TwilightForest 1.7.10 2.3.7

### ISSUE THREAD

**Issue by ExDomino** [Benimatic/twilightforest#35]
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at twilightforest.world.TFGenWitchHut.generateTinyHut(TFGenWitchHut.java:180)
	at twilightforest.world.TFGenWitchHut.func_76484_a(TFGenWitchHut.java:18)
	at twilightforest.biomes.TFBiomeDecorator.func_150513_a(TFBiomeDecorator.java:158)
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:114)
	at twilightforest.biomes.TFBiomeDecorator.func_150512_a(TFBiomeDecorator.java:139)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at twilightforest.biomes.TFBiomeFireSwamp.func_76728_a(TFBiomeFireSwamp.java:63)
	at net.minecraft.world.gen.ChunkProviderFlat.func_73153_a(SourceFile:162)
	at com.rwtema.extrautils.worldgen.Underdark.ChunkProviderUnderdark.func_73153_a(ChunkProviderUnderdark.java:50)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:384)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:269)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:189)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:157)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:280)
	at net.minecraft.world.World.func_72964_e(World.java:751)
	at net.minecraft.world.World.func_147439_a(World.java:677)
	at mods.natura.worldgen.CloudGen.func_76484_a(CloudGen.java:44)
	at mods.natura.worldgen.BaseCloudWorldgen.generate(BaseCloudWorldgen.java:68)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:414)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:269)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:189)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:157)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:280)
	at net.minecraft.world.World.func_72964_e(World.java:751)
	at net.minecraft.world.World.func_147439_a(World.java:677)
	at net.minecraft.world.World.func_147437_c(World.java:697)
	at mods.natura.worldgen.BaseCropWorldgen.generateBarley(BaseCropWorldgen.java:147)
	at mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:46)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137)
	at com.rwtema.extrautils.worldgen.Underdark.ChunkProviderUnderdark.func_73153_a(ChunkProviderUnderdark.java:56)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:384)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)

**Comment by liach** [comment]
ExtraUtil issue

**Comment by ExDomino** [comment]
Ok I'll report to them: https://github.com/rwtema/extrautilities/issues/743

**Comment by Benimatic** [comment]
Oof, yeah, you're getting TF biomes in the overworld, which are then generating in the underdark. So I guess I'm not quite sure where the error lies.
