### ISSUE TITLE
random crash in a modpack

### ISSUE THREAD

**Issue by micahlaster98** [Benimatic/twilightforest#61]
at random times playing a mod pack i get crashes that seem to be coming from 
at twilightforest.entity.boss.EntityTFNagaSegment.collideWithOthers(EntityTFNagaSegment.java:154)
at twilightforest.entity.boss.EntityTFNagaSegment.func_70071_h_(EntityTFNagaSegment.java:109)
i was wondering if you could tell me what is going on here

pastebin of crash repport file
http://pastebin.com/Fvg4Bp6s

**Comment by Bogdan-G** [comment]
empty entity/de-sync
