### ISSUE TITLE
Hello, my server crashed

### ISSUE THREAD

**Issue by xlch88** [Benimatic/twilightforest#66]
The following is an crash report

`---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 17-7-17 下午9:32
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:131)
	at twilightforest.biomes.TFBiomeDecorator.func_150513_a(TFBiomeDecorator.java:208)
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:114)
	at twilightforest.biomes.TFBiomeDecorator.func_150512_a(TFBiomeDecorator.java:139)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at twilightforest.biomes.TFBiomeTwilightForestVariant.func_76728_a(TFBiomeTwilightForestVariant.java:86)
	at twilightforest.world.ChunkProviderTwilightForest.func_73153_a(ChunkProviderTwilightForest.java:977)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:419)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1202)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:303)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:208)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:170)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:315)
	at net.minecraft.world.World.func_72964_e(World.java:751)
	at net.minecraft.world.World.func_147439_a(World.java:677)
	at net.minecraft.block.BlockGrass.func_149674_a(BlockGrass.java:77)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:569)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:288)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:131)
	at twilightforest.biomes.TFBiomeDecorator.func_150513_a(TFBiomeDecorator.java:208)
	at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:114)
	at twilightforest.biomes.TFBiomeDecorator.func_150512_a(TFBiomeDecorator.java:139)
	at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
	at twilightforest.biomes.TFBiomeTwilightForestVariant.func_76728_a(TFBiomeTwilightForestVariant.java:86)
	at twilightforest.world.ChunkProviderTwilightForest.func_73153_a(ChunkProviderTwilightForest.java:977)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:419)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1202)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:303)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:208)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:170)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:315)
	at net.minecraft.world.World.func_72964_e(World.java:751)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (-799,29,-1168), Chunk: (at 1,1,0 in -50,-73; contains blocks -800,0,-1168 to -785,255,-1153), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:677)
	at net.minecraft.block.BlockGrass.func_149674_a(BlockGrass.java:77)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:569)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:288)

-- Affected level --
Details:
	Level name: DIM7
	All players: 1 total; [EntityPlayerMP['Newlife'/46534, l='DIM7', x=-728.06, y=31.15, z=-1189.58](Newlife at -728.0577929955817,31.14549273206596,-1189.5805103759972)]
	Chunk stats: ServerChunkCache: 106 Drop: 0
	Level seed: -5495155374254661483
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,30,0), Chunk: (at 0,1,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3186062 game time, 4540958 day time
	Level dimension: 7
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 113378 (now: false), thunder time: 148333 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:931)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1614.201 Official
	Plugins: HiveJumpPads, RPGItems, GroupManager, VoidWorld, NametagEdit, Void2Spawn, VoxelSniper, BanItem, Yum, AT, BossShop, RichAutoMessage, CoreProtect, PlayerHeads, WorldEdit, FrameProtect, urusai, FirstJoinPlus, Essentials, EffectEdit, Promotion, SlashFixer, WorldBorder, ChopTreeW, LaggRemover, ProtocolLib, RedPacket, OpenBox, AntiAttack, EssentialsChat, SQLibrary, VLagger, AnvilColors, RandomTp, Vault, Clogin, ScriptBlock, PixelVip, NeverLag, LWC, QuickShop, PlayerPoints, CustomGiftCode, ChestCommands, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, PlotMe, ColorMOTD, GreatFireWall, Residence, GlobalMarket, PlotMe-DefaultGenerator, Multiverse-Core, AncientGates, HolographicDisplays, HolographicDisplaysPatch
	Disabled Plugins: 
	Operating System: Windows Server 2008 R2 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1882158968 bytes (1794 MB) / 3085434880 bytes (2942 MB) up to 9320792064 bytes (8889 MB)
	JVM Flags: 4 total; -Xmx10000m -Xms3000m -XX:+AggressiveOpts -XX:+UseCompressedOops
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 7336, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.201.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.201.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	OldModelLoader{1.0} [OldModelLoader] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.10} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	NBTEdit{1.7.2.2} [In-game NBTEdit] ([NBT修改器]NBTEdit_1.7.10.jar) 
	UCHIJAAAA	colourfulportalsmod{1.4.3} [Colourful Portals] ([传送门]ColourfulPortals-1.4.3.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] ([暮色森林]twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] ([凿]Chisel-2.9.5.11.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] ([前置]AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	llibrary{1.5.1} [LLibrary] ([前置]llibrary-1.5.1-1.7.10.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] ([前置]MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAA	animalbikes{1.7.10} [Animal Bikes] ([动物坐骑]AnimalBikes_1.7.10.jar) 
	UCHIJAAAA	animalsPlus{1.2} [Animals+] ([动物附加]animalsPlus-1.2cn.jar) 
	UCHIJAAAA	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] ([和风]BambooMod.jar) 
	UCHIJAAAA	lmmx{1.0} [lmmx] ([女仆]littleMaidMobX-1.7.x_0.1.3a.jar) 
	UCHIJAAAA	MMMLibX{1.7.x-srg-1} [MMMLibX] ([女仆]littleMaidMobX-1.7.x_0.1.3a.jar) 
	UCHIJAAAA	zabuton{1.0} [zabuton] ([女仆]littleMaidMobX-1.7.x_0.1.3a.jar) 
	UCHIJAAAA	cfm{3.4.8} [MrCrayfish's Furniture] ([家具]MrCrayfish's Furniture 3.4.8.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] ([展示架]BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	OpenMods{0.10} [OpenMods] ([开放MOD前置]OpenModsLib-1.7.10-0.10.jar) 
	UCHIJAAAA	OpenBlocks{1.6} [OpenBlocks] ([开放方块]OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] ([拔刀剑]SlashBlade-mc1.7.10-r87.jar) 
	UCHIJAAAA	balumg{1.0.0} [balumg] ([拔刀剑附属]Balmung+1.7.10-r1.0-1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.blademaster{mc1.7.2-r1} [BladeMaster] ([拔刀剑附属]BladeMaster-mc1.7.2-r1.2.jar) 
	UCHIJAAAA	flammpfeil.darkraven{mc1.7.2-r2} [DarkRaven] ([拔刀剑附属]DarkRaven-mc1.7.2-r2.jar) 
	UCHIJAAAA	flammpfeil.fluorescentbar{mc1.7.2-r3} [fluorescentbar] ([拔刀剑附属]fluorescentbar-mc1.7.2-r3.jar) 
	UCHIJAAAA	flammpfeil.nihil{mc1.7.x-r8} [Nihil] ([拔刀剑附属]Nihil-mc1.7.x-r8.jar) 
	UCHIJAAAA	flammpfeil.slashblade.anvilenchant{mc1.7.10-r1} [Slashblade-AnvilEnchant] ([拔刀剑附属]Slashblade-AnvilEnchant-mc1.7.10-r1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.kamuy{mc1.7.10-r6} [Kamuy] ([拔刀剑附属]SlashBlade-Kamuy-mc1.7.10-r6.jar) 
	UCHIJAAAA	flammpfeil.slashblade.kirisaya{r1} [SlashBlade-Kirisaya] ([拔刀剑附属]SlashBlade-Kirisaya-r1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.laemmle{mc1.7.10-r1} [Slashblade-Laemmle] ([拔刀剑附属]Slashblade-Laemmle-mc1.7.10-r1.jar) 
	UCHIJAAAA	slashblade.yukari{mc1.7.10-r2} [Slashblade-yukari] ([拔刀剑附属]Slashblade-yukari-mc1.7.10-r2.jar) 
	UCHIJAAAA	flammpfeil.frostwolf{mc1.7.2-r1} [FrostWolf] ([拔刀剑附属]SlashBladeFrostWolf-mc1.7.2-r1.1.jar) 
	UCHIJAAAA	flammpfeil.slashbladewa{mc1.7.2-r1} [SlashBladeWa] ([拔刀剑附属]SlashBladeWa-mc1.7.2-r1.jar) 
	UCHIJAAAA	flammpfeil.slashblade.wanderer{mc1.7.2-r1} [SlashBladeWanderer] ([拔刀剑附属]SlashBladeWanderer-mc1.7.2-r1.jar) 
	UCHIJAAAA	flammpfeil.toyako{mc1.7.2-r1} [toyako] ([拔刀剑附属]toyako-mc1.7.2-r1.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.43.1.531} [Armourer's Workshop] ([时装工坊]Armourers-Workshop-1.7.10-0.43.1.531.jar) 
	UCHIJAAAA	plushieWrapper{0.0.0} [Plushie Wrapper] ([时装工坊]Armourers-Workshop-1.7.10-0.43.1.531.jar) 
	UCHIJAAAA	erebus{0.4.7} [Erebus] ([昆虫异界]TheErebus-0.4.7.jar) 
	UCHIJAAAA	ExtrabiomesXL{3.16.4} [ExtrabiomesXL] ([更多地形]extrabiomesxl_1.7.10-3.16.4.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] ([更多箱子]IronChest-6.0.62.742.jar) 
	UCHIJAAAA	me{1.3.2.1} [More Enchantments] ([更多附魔]MoreEnchantments-1.7.10-1.3.2.1.jar) 
	UCHIJAAAA	AencEx{0.0.1} [AencEx] ([更多附魔]MoreEnchantments-1.7.10-1.3.2.1.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.8} [Carpenter's Blocks] ([木匠]Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
	UCHIJAAAA	mod_ecru_MapleTree{1.1.33e} [MapleTree] ([枫树]MapleTree Forge v1.1.33e.jar) 
	UCHIJAAAA	HopperDuctMod{1.3.2} [Hopper Ducts] ([漏斗管道]hopperductmod-1.7.10-1.3.2.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] ([潘马斯的世界]Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	nolpfij_mobstatues{0.1.1} [mobstatues] ([生物雕像]MobStatues-1.7.10-0.1.1.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] ([电脑]ComputerCraft1.75.jar) 
	UCHIJAAAA	crazyores{2.0.7} [CrazyOres] ([疯狂的矿物]CrazyOres V2.0.7.jar) 
	UCHIJAAAA	fantastic{1.0.0} [Fantastic Fish] ([神奇的鱼]Fantastic Fish1.4.jar) 
	UCHIJAAAA	MutantCreatures{1.4.9} [Mutant Creatures] ([突变生物]MutantCreatures-1.7.10-1.4.9.jar) 
	UCHIJAAAA	InfernalMobs{1.5.9} [Infernal Mobs] ([精英怪物]InfernalMobs1.5.9-1.7.10.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] ([红石计划]ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] ([红石计划]ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] ([红石计划]ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] ([红石计划]ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] ([红石计划]ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] ([红石计划]ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] ([红石计划]ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] ([红石计划]ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] ([红石计划]ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJAAAA	cosmeticWings{1.7.10-0.4.2.17} [Cosmetic Wings] ([翅膀ww]Cosmetic-Wings-Mod-1.7.10.jar) 
	UCHIJAAAA	mowziesmobs{1.2.9} [Mowzie's Mobs] ([脑洞大开的生物]MowziesMobs-1.2.99.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] ([自定义npc]CustomNPCs_1.7.10d(19jun17).jar) 
	UCHIJAAAA	ForgottenNature{1.7.19} [Forgotten Nature] ([被遗忘的大自然]ForgottenNature_1.7.19old.jar) 
	UCHIJAAAA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] ([魔典盖亚]GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	UCHIJAAAA	ea{v2.3.4c-mc1.7.10} [Ebon Arts] ([黑檀工艺]EbonArts-v2.3.4c-mc1.7.10_XlchCN.jar) 
	UCHIJAAAA	custommc{1.0v} [custommc] (CustomMc.jar) 
	UCHIJAAAA	MCEF{0.6} [Minecraft Chromium Embedded Framework] (MCEF-[汉化by+Sohoad]1.7.10-0.6.jar) 
	UCHIJAAAA	WebDisplay{0.11} [Web Displays] (Web-Displays-Mod-MCEF-[汉化by+Sohoad]1.7.10.0.11.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[player_damage_hook:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 4 / 100; [EntityPlayerMP['Glasses'/42103, l='world', x=86.70, y=27.00, z=343.98](Glasses at 86.69999998807907,27.0,343.98323271913324), EntityPlayerMP['Newlife'/46534, l='DIM7', x=-728.06, y=31.15, z=-1189.58](Newlife at -728.0577929955817,31.14549273206596,-1189.5805103759972), EntityPlayerMP['YuanZhang_'/50461, l='world', x=81.56, y=60.00, z=438.34](YuanZhang_ at 81.56485822345623,60.0,438.3411723957262), EntityPlayerMP['xcheng'/61222, l='world', x=2571.50, y=11.00, z=884.16](xcheng at 2571.503033037746,11.0,884.1638854581234)]
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by Bogdan-G** [comment]
If restart - normal work? Go test TF version: https://www.dropbox.com/s/exi4hum0fib5hmh/twilightforest-1.7.10-2.3.8dev.jar?dl=0
