### ISSUE TITLE
[1.11.2] Immutable Collection exception when mods add mobs.

### ISSUE THREAD

**Issue by Tokeli** [Benimatic/twilightforest#67]
Forge: 13.20.1.2386
Mods:
Twilight Forest 1.11.2-2.4.0-140-Universal
CTM 1.11.2-0.2.2.12
EnderZoo 1.11.2-1.3.0.47
Quark r1.2-93b

Startup will crash (but has succeeded once or twice?) when either of these mods try to register mobs. Presumably other mods too, but I didn't test the rest of my pack. Remove TF and everything is fine. Notably, it started up once at random with no issue?

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.11.2-0.2.2.12.jar)
  LoadingPlugin (Quark-r1.2-93b.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 8/20/17 4:06 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Quark (quark)
Caused by: java.lang.UnsupportedOperationException
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:96)
	at net.minecraftforge.fml.common.registry.EntityRegistry.addSpawn(EntityRegistry.java:253)
	at vazkii.quark.world.feature.DepthMobs.preInit(DepthMobs.java:60)
	at vazkii.quark.base.module.Module.lambda$preInit$1(Module.java:128)
	at vazkii.quark.base.module.Module$$Lambda$50/434612827.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at vazkii.quark.base.module.Module.forEachEnabled(Module.java:183)
	at vazkii.quark.base.module.Module.preInit(Module.java:128)
	at vazkii.quark.base.module.ModuleLoader.lambda$preInit$2(ModuleLoader.java:80)
	at vazkii.quark.base.module.ModuleLoader$$Lambda$49/2116948345.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at vazkii.quark.base.module.ModuleLoader.forEachEnabled(ModuleLoader.java:157)
	at vazkii.quark.base.module.ModuleLoader.preInit(ModuleLoader.java:80)
	at vazkii.quark.base.proxy.CommonProxy.preInit(CommonProxy.java:29)
	at vazkii.quark.base.proxy.ClientProxy.preInit(ClientProxy.java:39)
	at vazkii.quark.base.Quark.preInit(Quark.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:276)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 68477680 bytes (65 MB) / 289542144 bytes (276 MB) up to 4151836672 bytes (3959 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m -XX:+UseParNewGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2386 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2386.jar) 
	UCH	forge{13.20.1.2386} [Minecraft Forge] (forge-1.11.2-13.20.1.2386.jar) 
	UCE	quark{r1.2-93} [Quark] (Quark-r1.2-93b.jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCH	ctm{MC1.11.2-0.2.2.12} [CTM] (CTM-MC1.11.2-0.2.2.12.jar) 
	UCH	enderzoo{1.11.2-1.3.0.47} [Ender Zoo] (EnderZoo-1.11.2-1.3.0.47.jar) 
	UCH	jei{4.5.0.294} [Just Enough Items] (jei_1.11.2-4.5.0.294.jar) 
	UCH	theoneprobe{1.4.14} [The One Probe] (theoneprobe-1.1x-1.4.14.jar) 
	UCH	twilightforest{2.3.8dev} [The Twilight Forest] (twilightforest-1.11.2-2.4.0.140-universal.jar) 
	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.11.2-0.2.2.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Quark-r1.2-93b.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 970/PCIe/SSE2'
```
Or a link: https://gist.github.com/Tokeli/82306b70a6135baee0841dad4f89e63a

**Comment by Tamaized** [comment]
Fixed in https://github.com/TeamTwilight/twilightforest/commit/43aabd430add5231ea63c46b80d2375ea8f6fd31
